### ISSUE TITLE
KeyError: 'Tr' reported 

### ISSUE THREAD

**Issue by weiliuxm** [valeoai/xmuda#10]
I encountered the following error when preprocessing the semanticKITTI
`Traceback (most recent call last):
  File "xmuda/data/semantic_kitti/preprocess.py", line 176, in <module>
    preprocess('val', root_dir, out_dir)
  File "xmuda/data/semantic_kitti/preprocess.py", line 133, in preprocess
    dataloader = DataLoader(DummyDataset(root_dir, split), num_workers=8)
  File "xmuda/data/semantic_kitti/preprocess.py", line 22, in __init__
    self.glob_frames(scenes)
  File "xmuda/data/semantic_kitti/preprocess.py", line 29, in glob_frames
    calib = self.read_calib(osp.join(self.root_dir, 'dataset', 'sequences', scene, 'calib.txt'))
  File "xmuda/data/semantic_kitti/preprocess.py", line 69, in read_calib
    calib_out['Tr'][:3, :4] = calib_all['Tr'].reshape(3, 4)
KeyError: 'Tr'
`
Best regards,
Wei

**Comment by maxjaritz** [comment]
Does my comment in this previous issue help? #2

**Comment by weiliuxm** [comment]
Thank you.  Now it works.
